package example;


/**
* example/_FibonacciStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/yo_BM/3D Objects/Ramon Parcial 3/corba-main/corba-main/CorbaFiboInterface/src/fibonacci.idl
* viernes 13 de agosto de 2021 05:25:30 PM CDT
*/

public class _FibonacciStub extends org.omg.CORBA.portable.ObjectImpl implements example.Fibonacci
{


  /* Codigo fibonacci CORBA
		* in: el valor del parametro se le envia el
		* cliente al servidor
		* long: -231...231-1 (32bits)
		* numero: nombre de la variable
		*/
  public String generar (int numero)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("generar", true);
                $out.write_long (numero);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return generar (numero        );
            } finally {
                _releaseReply ($in);
            }
  } // generar

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:example/Fibonacci:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _FibonacciStub
