package example;


/**
* example/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/yo_BM/3D Objects/Ramon Parcial 3/corba-main/corba-main/CorbaFiboInterface/src/fibonacci.idl
* viernes 13 de agosto de 2021 05:25:30 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
