package example;


/**
* example/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/yo_BM/3D Objects/Ramon Parcial 3/corba-main/corba-main/CorbaFiboInterface/src/fibonacci.idl
* viernes 13 de agosto de 2021 05:25:30 PM CDT
*/

public interface FibonacciOperations 
{

  /* Codigo fibonacci CORBA
		* in: el valor del parametro se le envia el
		* cliente al servidor
		* long: -231...231-1 (32bits)
		* numero: nombre de la variable
		*/
  String generar (int numero);
} // interface FibonacciOperations
